name = "Create-Delight-Project-Rebirth"
author = "JSI"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7587bf97f36c65d2b7aadd26adf4266d884471ea7d64741619be881685360d9d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
