name = "Create-Delight-Project-Rebirth"
author = "JSI"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0bb5535219269fad55b8d6043bc2f1cf9e11a9324d2f4fb63e178cef4772b0e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
