VersionLiteLoader:False
VersionFabric:
VersionForge:
Info:齿轮盛宴R
VersionVanilla:21.0.1
LogoCustom:True
VersionAdvanceDisableModUpdate:False
VersionAdvanceJvm:-Dfile.encoding=UTF-8
CustomInfo:齿轮盛宴R
VersionVanillaName:1.21.1
ReleaseTime:2024-08-08 20:24
VersionNeoForge:21.1.228
Logo:PCL\Logo.png
VersionOptiFine:
VersionArgumentIndieV2:True
State:7
